### ISSUE TITLE
Add YAML structure validation

### ISSUE THREAD

**Issue by chuckha** [chuckha/kepview#1]
Use the function defined in the YAML library `UnmarshalYAML(func(interface{})error) error` to check for YAML structure validation for the metadata types. This will allow us to return a friendly user error and say things like "Authors must be a list of users, not a map" or something like that.

Note this is different than data validation

**Comment by alexbrand** [comment]
@chuckha Are you thinking we should have a custom unmarshaller for the Proposal type that will intercept the errors we get from the YAML library to rewrite them in a user-friendly format?

I am also wondering if it would make sense to use something like OpenAPI and its validation toolkit (https://github.com/go-openapi/validate), although that might be too heavyweight.

**Comment by chuckha** [comment]
open api validate would require us to actually build out an API for the metadata type which might be nice but would be heavyweight.

I'm thinking about closing this issue and just focusing on data validation for now. YAML library doesn't give us a good way to surface structural errors. It already returns the line that breaks the Parser which should be enough for someone to understand why the YAML is broken.

Yeah, I think I've convinced myself in this comment. Data validations are the important one.

**Comment by chuckha** [comment]
of course as soon as i type that i realized i was parsing the yaml in a no so smart way. improvements which i think are pretty good! 

https://github.com/chuckha/kepview/commit/b1b01d59f9cfdf227df199e222a1666104e7ed3b
