### ISSUE TITLE
Add data validation

### ISSUE THREAD

**Issue by chuckha** [chuckha/kepview#2]
After the YAML is parsed into a Proposal object we should run some validations on the data. The errors returned here should be friendly and actionable to the user as they may see them as the result of a prow pull job (a job run on every pull request).

There are some open questions regarding the metadata object found in https://github.com/kubernetes/enhancements/blob/master/keps/YYYYMMDD-kep-template.md

```
---
title: KEP Template
authors:
  - "@janedoe"
owning-sig: sig-xxx
participating-sigs:
  - sig-aaa
  - sig-bbb
reviewers:
  - TBD
  - "@alicedoe"
approvers:
  - TBD
  - "@oscardoe"
editor: TBD
creation-date: yyyy-mm-dd
last-updated: yyyy-mm-dd
status: provisional|implementable|implemented|deferred|rejected|withdrawn|replaced
see-also:
  - "/keps/sig-aaa/20190101-we-heard-you-like-keps.md"
  - "/keps/sig-bbb/20190102-everyone-gets-a-kep.md"
replaces:
  - "/keps/sig-ccc/20181231-replaced-kep.md"
superseded-by:
  - "/keps/sig-xxx/20190104-superceding-kep.md"
---
```

@justaugustus -- what in the metadata is optional and what is required?

**Comment by justaugustus** [comment]
Hey @chuckha!
The following fields are optional: `participating-sigs`, `editor`, `see-also`, `replaces`, `superseded-by`

Thanks for hacking on this! :)

**Comment by chuckha** [comment]
fixed at some point recently
